Try fixing nixpkgs-in-module error
Setting nixpkgs.overlays within the NixOS module produces the following
error on nixos-rebuild.

error: Module `:anon-1347:anon-1' has an unsupported attribute
`nixpkgs'. This is caused by introducing a top-level `config' or
`options' attribute. Add configuration attributes immediately on the top
level instead, or move all of them (namely: nixpkgs) into the explicit
`config' attribute.